anaxago_core:
    resource: "@AnaxagoCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: AnaxagoCoreBundle:Security:login }

logout:
    path: /logout

anaxago_core_registration:
    path: /register
    defaults: { _controller: AnaxagoCoreBundle:Security:registration }

get_projets:
    path: /api/projects
    methods: ['GET']
    defaults: { _controller: AnaxagoCoreBundle:Project:get }

create_interest:
    path: /api/interests
    methods: ['POST']
    defaults: { _controller: AnaxagoCoreBundle:Interest:post }

get_interests:
    path: /api/interests
    methods: ['GET']
    defaults: { _controller: AnaxagoCoreBundle:Interest:get }
